### PR TITLE
Add support for the ACF Table field Plugin where enabled.

### PR DESCRIPTION
**Pull request by jeremyProwseYS**
https://wordpress.org/plugins/advanced-custom-fields-table-field/

### CODE REVIEW

**Comment by marco910** [comment]
Any updates on this?

**Comment by jeremyProwseYS** [comment]
@marco910 Unsure if anyone is actively looking into reviewing this PR as it has been over 14 months since it was created. If you require this functionality and would like to use the latest versions of wp-graphql-acf (definitely advised) then you should relatively easily be able to turn this into it's own plugin that enables the support, much like many of the other add-on plugins for wp-graphql.

**Comment by jeremyProwseYS** [comment]
@jasonbahl unsure if there are any issues surrounding this pull request, or if my comment above is accurate to this being better suited as it's own plugin. Either way just bumping this.

**Review by aresrioja10 — APPROVED** [review]

**Comment by aresrioja10** [comment]
@jasonbahl That looks ok to me. Could this be merged?

**Comment by bkthigpen** [comment]
@jasonbahl @aresrioja10 @jeremyProwseYS It would be amazing it we could get official support for `acf-tables` since it's a real necessity for my team.

**Comment by marco910** [comment]
I created a simple plugin that extends the current `wp-graphql-acf` plugin with the support for the "Table" field. The code looks like this:

```
/**
 * Exit if file is accessed directly
 */
if (!defined('ABSPATH')) {
    exit;
}


/**
 * Import helper functions if not exists
 */
if (!function_exists('is_plugin_active')) {
    include_once(ABSPATH . 'wp-admin/includes/plugin.php');
}


/**
 * Only do add actions if any necessary plugin are acitivated and not missing.
 */
if (
    is_plugin_active("wp-graphql/wp-graphql.php") &&
    is_plugin_active("wp-graphql-acf-develop/wp-graphql-acf.php") &&
    is_plugin_active("advanced-custom-fields-table-field/acf-table.php")
) {
    /**
     * Register object type in GraphQL
     */
    add_action('graphql_register_types', function () {
        register_graphql_object_type('ACF_Table', [
            'fields' => [
                'headerEnabled' => [
                    'type' => 'Boolean'
                ],
                'header' => [
                    'type' => [
                        'list_of' => 'String'
                    ]
                ],
                'body' => [
                    'type' => [
                        'list_of' => [
                            'list_of' => 'String'
                        ]
                    ]
                ],
            ],
        ]);
    });

    // Add field-resolver
    add_filter('wpgraphql_acf_register_graphql_field', function (
        $fieldConfig,
        $typeName,
        $fieldName,
        $config
    ) {
        $getValue = $fieldConfig['resolve'];

        if ('table' == $config['acf_field']['type']) {
            return [
                'type'    => 'ACF_Table',
                'resolve' => function ($root, $args = [], \WPGraphQL\AppContext $context, $info) use ($getValue) {
                    $value = $getValue($root, $args, $context, $info);

                    // No table data, return `null`
                    if (!$value) return null;

                    // Return table data
                    return [
                        'headerEnabled' => $value['p']['o']['uh'] === 1,
                        'header'  => 1 == $value['p']['o']['uh'] ? array_map(function ($th) {
                            return $th['c'];
                        }, $value['h']) : [],
                        'body' => array_map(function ($row) {
                            return array_map(function ($cell) {
                                return $cell['c'];
                            }, $row);
                        }, $value['b']),
                    ];
                },
            ];
        }

        return $fieldConfig;
    }, 10, 4);

    // Add to supported fields
    add_filter('wpgraphql_acf_supported_fields', function ($fields) {
        $fields[] = 'table';
        return $fields;
    });
}
```

This is the data returned by GraphQL:
```
"table": {
  "headerEnabled": true,
  "header": [
    "Header Row 1 Col A",
    "Header Row 1 Col B"
  ],
  "body": [
    [
      "Body Row 1 Col A",
      "Body Row 1 Col B"
    ],
    [
      "Body Row 2 Col A",
      "Body Row 2 Col B"
    ]
  ]
}
```
Of course, this is not a pretty nice solution, but it works. A much better way would be if @jasonbahl could add support for this directly into the plugin.

**Comment by jeremyProwseYS** [comment]
@marco910 I can see the benefits of both approaches.

- On the one hand it doesn't exactly hurt to have the code in main repo for wp-graphql-acf as it would sit behind a conditional and never run unless tables was enabled anyway.
- However this is also a bit of an edge case in the sense that there is no need for the code to be in the repo unless you are using the tables plugin (and how many people actually are in this configuration). So an approach where the acf-table graphql support is in a stand-alone plugin isn't necessarily a bad idea.

Either way works, the main thing is that a decision is made on where this code should live, and access to it made readily available for those looking to implement it.

**Comment by jasonbahl** [comment]
Since there are [hundreds of ACF Extensions](https://www.awesomeacf.com/), I don't want to get in the business of maintaining and guaranteeing support for all of the extensions. It's a lot of technical debt and maintenance overhead. (I'm already struggling to keep this repo in good condition as-is 🤦🏻‍♂️)

I think long-term it makes sense for extension plugins to maintain the code to expose their data to the GraphQL schema in their extension. i.e. the table extension would include a snippet such as that provided by @marco910 in the table extension itself and if it's active at the same time as WPGraphQL, it all works. 

If the acf extension doesn't want to maintain support, a standalone wp-graphql-acf-table extension could be supported, or even another repo could be started specifically for extension plugins to be supported.

**Pull request closed without merging**
