### PR TITLE
use required property to determinate non_null type

### PR DESCRIPTION
**Pull request by DevTrong**
### Issue

Currently every generated fields in the schema is nullable, even though the field was marked as required.

```
type CustomType {
  title: String
}
```

With this PR it checks the `required` or/and the `allow_null` property and generates the schema properly.

```
type CustomType {
  title: String!
}
```

### Motivation
When using the schema to generate types (eg. for TypeScript), every type is nullable, which makes it unusable with the `strict` option in TypeScript.

This is the result from the generated type:
```
interface CustomType {
  title: string | null;
}
```

### CODE REVIEW

**Comment by manspaniel** [comment]
I'd love to see this feature merged! We're also using TypeScript generation, and basically any property access requires the optional chaining `?.` operator to bypass `Object is possibly null or undefined` TS errors. Given how deeply nested GraphQL schemas tend to be, that's a lot of `?.` operators... Makes total sense for optional fields, but not at all for required fields as far as I can tell.

**Comment by samuelsurgeon** [comment]
Ditto above. Also having the same issue as above in my own project.

**Comment by stefanpl** [comment]
Is there any chance somebody could take a look at this? If I can assist in any way, let me know … would be oh so sweet to have this merged 🙏

**Comment by elliott-w** [comment]
@jasonbahl Are there any reasons to not merge this? Would be very helpful

**Comment by elliott-w** [comment]
For those who stumble across this, I've used this utility type to recursively force all typescript properties to be required:
```ts
export type DeepRequired<T> = {
  [K in keyof T]-?: DeepRequired<NonNullable<T[K]>>
}
```

**Comment by jasonbahl** [comment]
Here's my current thoughts on why I'm leaning toward _not_ supporting this as-is. 

There are many cases where fields are nullable, even if marked required. 

There are a lot of cases in WordPress where data could actually **not** exist for a field, even if it were marked required by ACF. 

Marking it required in ACF means that going forward, admins will need to submit the field to pass validation in the dashboard, but it doesn't guarantee data will be there. 

For example:
- posts (or other types of content) created before the field group was created/assigned to that location
- data imported from other sources might not have values for the fields
- data created by other clients (CLI, etc) might not have values for the fields
- data created before the field was marked required (maybe it used to be optional, and was just changed to required?)

Because of these reasons, I don't think we should map the `required` attribute of an ACF field to the `nonNull` attribute on the WPGraphQL Schema. 

Here's steps to reproduce: 

1. Publish a few blog posts
2. Create an ACF Field Group with a `required` field and assign it to the `Post` type
3. Query for a list of posts, including the ACF Field Group and nonNull field

I have the following field group registered:

```php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_639778efa5a83',
	'title' => 'Non Null Field Group',
	'fields' => array(
		array(
			'key' => 'field_639778f0ec8ce',
			'label' => 'Non Null Field',
			'name' => 'non_null_field',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 1,
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'show_in_graphql' => 1,
	'graphql_field_name' => 'nonNullFieldGroup',
	'map_graphql_types_from_location_rules' => 0,
	'graphql_types' => '',
));

endif;	
```

### Query on v0.6.1

CleanShot 2022-12-12 at 12 03 11


### Query with this PR checked out

CleanShot 2022-12-12 at 12 01 52


----


If folks feel strongly enough about this feature, then we'd need to ensure we always resolve a non-null value, even for the cases where there actually is no data for a field and the field _actually_ is null / not-set (vs set as an empty value)

**Comment by jasonbahl** [comment]
I think in order to support this, we'd need: 

- more control over how to set a field to be nullable/non-null instead of deducing from the `required` / `all_null` configs, as there could be situations like I explained and demonstrated which would break your client applications. Possibly a setting on each field that lets you explicitly opt-in/out of the nullable / non-null mapping to the GraphQL Schema? 
- proper resolution to ensure null values aren't returned if they shouldn't be

**Comment by jasonbahl** [comment]
I've implemented this feature in the new version of this plugin (being worked on in a [different repo](https://github.com/wp-graphql/wpgraphql-acf), for now).

see: https://github.com/wp-graphql/wpgraphql-acf/pull/46

CleanShot 2023-07-07 at 10 49 55

I'm going to close this issue as it's addressed in the re-architecture of the plugin. Any features/bugs related to the implementation should be reported on that repo.

**Pull request closed without merging**
